name: Deploy Oracle Agent Filesystem

on:
  pull_request:
    paths:
      - 'config/fs_config.yml'
      - 'ansible/**'
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  validate-config:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed' || github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # El resto de tus pasos de validación...

  deploy:
    needs: validate-config
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible oci
          ansible-galaxy collection install oracle.oci
          
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
      - name: Run Ansible Playbook
        run: |
          ansible-playbook \
            -i "${{ secrets.SSH_HOST }}," \
            -u ${{ secrets.SSH_USER }} \
            --private-key=~/.ssh/id_rsa \
            ansible/playbooks/create_fs.yml